import { describe, expect, it } from 'vitest';

/**
 * Tests for recorder utility functions.
 * Since we don't have jsdom, we test the exported pure functions
 * that don't need a real DOM. The DOM-dependent recording is
 * tested manually in the extension itself.
 */

// Import the module to test extractable logic
// We'll test the selector-building and label-building by
// extracting the helper functions as importable utilities.

// For now, test the patterns used by the recorder:

describe('selector resilience patterns', () => {
  it('detects auto-generated hex IDs', () => {
    const isAutoGenerated = (id: string) =>
      /^[a-f0-9]{8,}$/i.test(id) ||
      /^:r[0-9a-z]+:$/.test(id) ||
      /^[a-z]+-[a-f0-9]{4,}$/i.test(id) ||
      id.length > 40;

    expect(isAutoGenerated('a1b2c3d4e5f6a7b8')).toBe(true); // hex
    expect(isAutoGenerated(':r1a:')).toBe(true); // React useId
    expect(isAutoGenerated('prefix-a1b2c3d4')).toBe(true); // framework-generated
    expect(isAutoGenerated('a'.repeat(41))).toBe(true); // too long

    expect(isAutoGenerated('email-field')).toBe(false); // human-readable
    expect(isAutoGenerated('login-form')).toBe(false);
    expect(isAutoGenerated('user_password')).toBe(false);
    expect(isAutoGenerated('q')).toBe(false);
  });

  it('escapes CSS special characters', () => {
    const cssEscape = (s: string) => s.replace(/["\\]/g, '\\$&');
    expect(cssEscape('normal')).toBe('normal');
    expect(cssEscape('has"quotes')).toBe('has\\"quotes');
    expect(cssEscape('has\\backslash')).toBe('has\\\\backslash');
  });

  it('selector tier ordering is correct', () => {
    // Verify our resilience tiers are in the right order
    const _tiers = ['id', 'testid', 'aria', 'label', 'text', 'css', 'xpath'];
    const confidences = [0.95, 0.95, 0.85, 0.8, 0.7, 0.4, 0.3];

    // Each tier should have decreasing confidence
    for (let i = 1; i < confidences.length; i++) {
      expect(confidences[i]).toBeLessThanOrEqual(confidences[i - 1]);
    }
  });
});

describe('testid detection patterns', () => {
  const TEST_ATTRS = ['data-testid', 'data-automation-id', 'data-test', 'data-cy', 'data-qa'];

  it('recognizes all common test ID attributes', () => {
    for (const attr of TEST_ATTRS) {
      // These are the attributes we check in buildSelectors
      expect(attr).toMatch(/^data-/);
    }
    expect(TEST_ATTRS).toHaveLength(5);
  });
});

describe('action type classification', () => {
  it('maps input events to correct action types', () => {
    // checkbox → check, select → select, other → fill
    const classify = (type: string, tagName: string) => {
      if (type === 'checkbox') return 'check';
      if (tagName === 'SELECT') return 'select';
      return 'fill';
    };

    expect(classify('checkbox', 'INPUT')).toBe('check');
    expect(classify('text', 'SELECT')).toBe('select');
    expect(classify('email', 'INPUT')).toBe('fill');
    expect(classify('password', 'INPUT')).toBe('fill');
    expect(classify('', 'TEXTAREA')).toBe('fill');
  });
});

describe('player selector resolution', () => {
  it('parses text: selectors', () => {
    const value = 'text:Sign In';
    const text = value.slice(5);
    expect(text).toBe('Sign In');
  });

  it('parses label-text: selectors', () => {
    const value = 'label-text:Email Address';
    const labelText = value.slice(11);
    expect(labelText).toBe('Email Address');
  });
});
