/**
 * Smart Action Recorder
 *
 * Records user actions on any page with multiple selector strategies.
 * Prioritizes resilient selectors (data-testid, aria-label, text content)
 * over fragile ones (CSS paths, xpath). This makes heuristics survive
 * minor page redesigns.
 *
 * Runs as part of the content script.
 */

import type { RecordedAction, SelectorStrategy } from './types';

let recording = false;
let actions: RecordedAction[] = [];
let lastActionTime = 0;
let onAction: ((action: RecordedAction) => void) | null = null;

/**
 * Build multiple selector strategies for an element, ordered by resilience.
 */
export function buildSelectors(el: Element): SelectorStrategy[] {
  const strategies: SelectorStrategy[] = [];

  // Tier 1: ID (most stable if present)
  if (el.id && !isAutoGenerated(el.id)) {
    strategies.push({ tier: 'id', value: `#${el.id}`, confidence: 0.95 });
  }

  // Tier 2: data-testid, data-automation-id (explicitly stable)
  for (const attr of ['data-testid', 'data-automation-id', 'data-test', 'data-cy', 'data-qa']) {
    const val = el.getAttribute(attr);
    if (val) {
      strategies.push({ tier: 'testid', value: `[${attr}="${val}"]`, confidence: 0.95 });
    }
  }

  // Tier 3: aria-label
  const ariaLabel = el.getAttribute('aria-label');
  if (ariaLabel) {
    strategies.push({
      tier: 'aria',
      value: `[aria-label="${cssEscape(ariaLabel)}"]`,
      confidence: 0.85,
    });
  }

  // Tier 4: Associated label (for inputs)
  if (
    el instanceof HTMLInputElement ||
    el instanceof HTMLTextAreaElement ||
    el instanceof HTMLSelectElement
  ) {
    const label = findLabel(el);
    if (label) {
      strategies.push({ tier: 'label', value: `label-text:${label}`, confidence: 0.8 });
    }

    // Name attribute (common in forms)
    if (el.name) {
      strategies.push({
        tier: 'css',
        value: `${el.tagName.toLowerCase()}[name="${cssEscape(el.name)}"]`,
        confidence: 0.75,
      });
    }

    // Type + placeholder combo
    const ph = el.getAttribute('placeholder');
    if (ph) {
      const type = el.getAttribute('type') ?? 'text';
      strategies.push({
        tier: 'css',
        value: `input[type="${type}"][placeholder="${cssEscape(ph)}"]`,
        confidence: 0.7,
      });
    }

    // Autocomplete attribute (very stable for form fields)
    const ac = el.getAttribute('autocomplete');
    if (ac && ac !== 'off') {
      strategies.push({ tier: 'css', value: `[autocomplete="${ac}"]`, confidence: 0.85 });
    }
  }

  // Tier 5: Text content (for buttons, links)
  if (
    el instanceof HTMLButtonElement ||
    el instanceof HTMLAnchorElement ||
    el.getAttribute('role') === 'button'
  ) {
    const text = el.textContent?.trim();
    if (text && text.length < 50) {
      strategies.push({ tier: 'text', value: `text:${text}`, confidence: 0.7 });
    }
  }

  // Tier 6: CSS selector (fallback, fragile)
  const cssPath = buildCssPath(el);
  if (cssPath) {
    strategies.push({ tier: 'css', value: cssPath, confidence: 0.4 });
  }

  return strategies;
}

/**
 * Build a human-readable label for the action.
 */
export function buildLabel(el: Element, actionType: string): string {
  const tag = el.tagName.toLowerCase();

  // For inputs: "Fill [Email] field" / "Click [Submit] button"
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const label = findLabel(el);
    const placeholder = el.getAttribute('placeholder');
    const name = label || placeholder || el.name || el.type || 'field';
    return actionType === 'fill' ? `Fill "${name}"` : `Click "${name}"`;
  }

  // For buttons/links: use text content
  const text = el.textContent?.trim().slice(0, 40);
  if (text) return `${actionType === 'click' ? 'Click' : actionType} "${text}"`;

  return `${actionType} ${tag}`;
}

/**
 * Start recording user actions.
 */
export function startRecording(callback: (action: RecordedAction) => void) {
  recording = true;
  actions = [];
  lastActionTime = Date.now();
  onAction = callback;

  document.addEventListener('click', handleClick, true);
  document.addEventListener('change', handleChange, true);
  document.addEventListener('keydown', handleKeydown, true);
}

/**
 * Stop recording, return all actions.
 */
export function stopRecording(): RecordedAction[] {
  recording = false;
  document.removeEventListener('click', handleClick, true);
  document.removeEventListener('change', handleChange, true);
  document.removeEventListener('keydown', handleKeydown, true);
  onAction = null;
  return actions;
}

export function isRecording(): boolean {
  return recording;
}

// --- Event handlers ---

function handleClick(e: MouseEvent) {
  if (!recording) return;
  const el = e.target as Element;
  if (!el || el.closest('[data-fags-ignore]')) return;

  const action = createAction(el, 'click');
  emit(action);
}

function handleChange(e: Event) {
  if (!recording) return;
  const el = e.target as HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;
  if (!el) return;

  if (el instanceof HTMLInputElement && el.type === 'checkbox') {
    const action = createAction(el, 'check');
    action.value = String(el.checked);
    emit(action);
  } else if (el instanceof HTMLSelectElement) {
    const action = createAction(el, 'select');
    action.value = el.value;
    emit(action);
  } else {
    const action = createAction(el, 'fill');
    action.value = el.value;
    emit(action);
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (!recording) return;
  // Only capture Enter and Tab as they trigger form submissions / focus changes
  if (e.key !== 'Enter' && e.key !== 'Tab') return;
  const el = e.target as Element;
  if (!el) return;

  const action = createAction(el, 'keypress');
  action.key = e.key;
  emit(action);
}

function createAction(el: Element, type: RecordedAction['type']): RecordedAction {
  const now = Date.now();
  const delay = lastActionTime ? now - lastActionTime : 0;
  lastActionTime = now;

  return {
    type,
    selectors: buildSelectors(el),
    delayMs: delay,
    label: buildLabel(el, type),
    url: location.href,
    timestamp: now,
  };
}

function emit(action: RecordedAction) {
  actions.push(action);
  onAction?.(action);
}

// --- Helpers ---

function findLabel(el: Element): string {
  // label[for=id]
  if (el.id) {
    const label = document.querySelector(`label[for="${CSS.escape(el.id)}"]`);
    if (label) return label.textContent?.trim() ?? '';
  }
  // Wrapping <label>
  const parent = el.closest('label');
  if (parent) {
    // Get label text without the input's own text
    const clone = parent.cloneNode(true) as Element;
    clone.querySelectorAll('input,textarea,select').forEach((n) => n.remove());
    return clone.textContent?.trim() ?? '';
  }
  // aria-labelledby
  const labelledBy = el.getAttribute('aria-labelledby');
  if (labelledBy) {
    const ref = document.getElementById(labelledBy);
    if (ref) return ref.textContent?.trim() ?? '';
  }
  return '';
}

function isAutoGenerated(id: string): boolean {
  // IDs that look auto-generated (hex, long numbers, React-style)
  return (
    /^[a-f0-9]{8,}$/i.test(id) ||
    /^:r[0-9a-z]+:$/.test(id) || // React useId
    /^[a-z]+-[a-f0-9]{4,}$/i.test(id) ||
    id.length > 40
  );
}

function cssEscape(s: string): string {
  return s.replace(/["\\]/g, '\\$&');
}

function buildCssPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;
  while (current && current !== document.body && parts.length < 5) {
    let selector = current.tagName.toLowerCase();
    if (current.id && !isAutoGenerated(current.id)) {
      selector = `#${current.id}`;
      parts.unshift(selector);
      break;
    }
    // Add nth-child for disambiguation
    const parent = current.parentElement;
    if (parent) {
      const siblings = Array.from(parent.children).filter((c) => c.tagName === current!.tagName);
      if (siblings.length > 1) {
        const idx = siblings.indexOf(current) + 1;
        selector += `:nth-of-type(${idx})`;
      }
    }
    parts.unshift(selector);
    current = current.parentElement;
  }
  return parts.join(' > ');
}
